---
collections:
  - name: stackhpc.cephadm
    version: 1.13.1
  - name: stackhpc.pulp
    version: 0.4.1
  - name: dellemc.openmanage
    version: 7.5.0
  - name: stackhpc.linux
    source: git+https://github.com/stackhpc/ansible-collection-linux.git,preemptive/vgpu-iommu
    type: git
  - name: stackhpc.hashicorp
    version: 2.3.0
roles:
  - src: stackhpc.sriov
    version: 0.2.0
  - src: stackhpc.grubcmdline
  - src: stackhpc.vxlan
  - name: ansible-lockdown.rhel8_cis
    src: https://github.com/ansible-lockdown/RHEL8-CIS
    version: 1.3.0
  - name: wazuh-ansible
    src: https://github.com/stackhpc/wazuh-ansible
    version: stackhpc
  - name: ansible-lockdown.ubuntu22_cis
    src: https://github.com/ansible-lockdown/UBUNTU22-CIS
    version: 2bbaefb3de539fc475f8924fc494857a2845c3fd
