---
# Setup of VF-LAG systemd configuration.
# This playbook should execute after kayobe overcloud host configure has completed.

- name: Enable SRIOV
  hosts: vflag
  tags:
    - sriov
  vars:
    # This playbook will execute after nodes are deployed
    # and before overcloud host configure - we can't assume
    # users and venvs exist.
    ansible_user: "ubuntu"
    ansible_python_interpreter: "/usr/bin/python3"
  handlers:
    - name: reboot
      set_fact:
        kayobe_needs_reboot: true
  tasks:
    # NOTE: define sriov_devices in group_vars
    - include_role:
        name: stackhpc.sriov
      vars:
        sriov_install_enabled: true
      when:
      - sriov_devices is defined
      - sriov_devices | length >= 0

- name: Prepare hosts for VF-LAG support
  hosts: vflag
  tags:
    - vflag
  vars:
    # This playbook will execute after nodes are deployed
    # and before overcloud host configure - we can't assume
    # users and venvs exist.
    ansible_user: "ubuntu"
    ansible_python_interpreter: "/usr/bin/python3"
  tasks:
    # TC offload requires kernel-modules-extra (act_ct module)
    - name: Ensure kernel-modules-extra is installed
      package:
        name: kernel-modules-extra
        state: present
      become: true
      when: ansible_facts.os_family == "RedHat"

    # /etc/sysconfig is a RedHat convention - create equivalent here
    - name: create /etc/sysconfig for Ubuntu
      become: true
      file:
        path: /etc/sysconfig
        owner: "root"
        group: "root"
        mode: 0755
        state: directory
      when: ansible_facts.os_family == "Debian"

    # Write /etc/sysconfig/sriov configuration to match this host
    - name: Define parameters in /etc/sysconfig/sriov
      template:
        src: "sysconfig-sriov.j2"
        dest: "/etc/sysconfig/sriov"
        owner: "root"
        group: "root"
        mode: 0755
      become: true
      notify: Reboot and wait

    - name: Transfer VF-LAG helper scripts to /usr/local/bin
      copy:
        src: "{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        owner: "root"
        group: "root"
        mode: 0755
      become: true
      with_items:
        - "mlnx-vflag-early"
        - "mlnx-vflag-final"
      notify: Reboot and wait

    - name: Transfer VF-LAG systemd units to /etc/systemd/system
      template:
        src: "{{ item }}.j2"
        dest: "/etc/systemd/system/{{ item }}"
        owner: "root"
        group: "root"
        mode: 0644
      become: true
      with_items:
        - "mlnx-vflag-early.service"
        - "mlnx-vflag-final.service"
      notify: Reboot and wait

    - name: Enable VF-LAG systemd units
      systemd:
        daemon_reload: true
        name: "{{ item }}"
        enabled: true
      become: true
      with_items:
        - "mlnx-vflag-early.service"
        - "mlnx-vflag-final.service"
      notify: Reboot and wait

    # There appears to be an issue where the reciprocal symlink from a
    # WantedBy= to a Wants= doesn't get created.  Explicitly ensure it exists.
    - name: Ensure the .wants symlink exists (Ubuntu)
      block:
        - file:
            path: "/etc/systemd/system/systemd-networkd.service.wants"
            state: "directory"
        - file:
            path: "/etc/systemd/system/systemd-networkd.service.wants/mlnx-vflag-early.service"
            src: "/etc/systemd/system/mlnx-vflag-early.service"
            state: "link"
      become: true
      when: ansible_facts.os_family == "Debian"

  handlers:
    - name: Reboot and wait
      set_fact:
        kayobe_needs_reboot: true
